### ISSUE TITLE
Finish Todos in README

### ISSUE THREAD

**Issue by kurzum** [dbpedia/links#12]

**Comment by RPOD** [comment]
Check 43f315b45c036dd5030ab809120757d3435bf4a4 if main README.md is ok

**Comment by kurzum** [comment]
"keep part here" and "link it"

+# /TODO/ description of further tools in the repo and how to access/execute them
+if too long keep part here and move the rest to individual readme and link it here

**Comment by kurzum** [comment]
this todo means how to run scripts for individual folders. 

/TODO/ How to update links for one dataset?

-- wie kann man fuer einen Ordner die links updaten 
-- describe how to execute validaterepo

**Comment by kurzum** [comment]
Todo steht noch drin
/TODO link for PDF, bibtex/

**Comment by kurzum** [comment]
last point is missing, link goes to wiki, but should go to section 3 of how to contribute page
interval of updates is missing, what time exactly,I said this in another conversation

/TODO/ How to download the monthly link release

-- download link -- describe publishing process, mention that details can be found in How to contribute links -- Server Update Script dokumentieren, so dass man ihn ausfuehren kann

**Comment by kurzum** [comment]
Your name is missing
/TODO Update/ Contributors (alphabetically)

**Comment by RPOD** [comment]
All todos should be worked on. Note that `validate.sh` can only be executed for all folders, it is very fast and currently throws no errors. The how to update is also mentioned either via a patch or update of the source through a pull request / change of the source the script is accessing. 
If something else is missing or should be changed please let me know.

**Comment by kurzum** [comment]
- bibtex is still missing
- I didn't check the "how to contribute" pages yet. Is there a good example that people can just copy?

**Comment by kurzum** [comment]
much better now though

**Comment by RPOD** [comment]
I tried to create an example for every file in the How To Contribute wiki page so it should be easy to understand. I will add the bibtex right away.
