### ISSUE TITLE
weekly/monthly updates are working

### ISSUE THREAD

**Issue by kurzum** [dbpedia/links#13]
Hi Robert, 
can you run the cronjob weekly for a while?
so we can check whether it works properly.

**Comment by RPOD** [comment]
The script should be running weekly for now.

**Comment by kurzum** [comment]
will close it, once I see it working

**Comment by RPOD** [comment]
You can execute the shell script on the server by navigating into `/etc/cron.monthly/` and executing the script. It will create a folder within the private `dbpedial-links` folder and then create a softlink into the public release folder.

**Comment by RPOD** [comment]
Should I create a script similar to the in issue #16 which will create the backlinks for each submitted linkset and add it within the script to commit the triples within their folders, or should it remain as an additional tool?

**Comment by kurzum** [comment]
working
