### ISSUE TITLE
structure download folder better

### ISSUE THREAD

**Issue by kurzum** [dbpedia/links#17]
Problem:
http://downloads.dbpedia.org/links/ has too many folders:
2016-10/                                           10-Oct-2016 08:23       -
links/                                             17-Oct-2016 17:32       -
tools/                                             17-Oct-2016 17:32       -
types/                                             17-Oct-2016 17:31       -
README.md    

should only contain:
2016-10/                                           10-Oct-2016 08:23       -

proposed solution: 
clone repo in a non-public  place, then link only the folder with the links vie ln -s

**Comment by RPOD** [comment]
Structure fixed. Automated script updated to create softlink

**Comment by kurzum** [comment]
a small thing, 2016-10 is 2016-10-01 ? 
what is the interval of the update script?

**Comment by RPOD** [comment]
Yes, it was from the first run where it still was monthly. Currently the interval is weekly on thursday. I will quickly rename the folder.

**Comment by kurzum** [comment]
hm, ok, maybe that with the bibtex was not clear, I added it to the readme
