### ISSUE TITLE
integrate Chile's Uri2Iri script

### ISSUE THREAD

**Issue by jimkont** [dbpedia/links#21]
https://github.com/dbpedia/extraction-framework/blob/master/scripts/src/main/scala/org/dbpedia/extraction/scripts/RecodeUris.scala

this needs to run as a post processing step

**Comment by chile12** [comment]
here the example call:
cd to $Extraction-Framework/scripts
../run RecodeUris  $yourLinkFolder .ttl.bz2 .ttl.bz2 true yourInput,Files,Comma,Separated,WithoutSuffix

**Comment by RPOD** [comment]
Added in e45fae9b9174cf7e1119c826e0a654f037b9d7ad , works already on server.
