### ISSUE TITLE
Generate a simple website for backlinks

### ISSUE THREAD

**Issue by kurzum** [dbpedia/links#25]
- protect with .htaccess and .htpwd
- sync on download server
- Table should have at least two columns with linkset name and download link for backlinks
- optionally the table could also link to the linkset in the repo and links download server

**Comment by RPOD** [comment]
Created the website with 8b0ea4b3d6970d2c2957d921c507abb2a1f535bb . It's also synced on the download server via the cron job, can be seen [here](http://downloads.dbpedia.org/links/backlinks/table.html)
Currently:
* backlinks throw 403
* .htaccess and .htpwd needs to be set up

Should something be changed?

**Comment by RPOD** [comment]
.htaccess and .htpwd has been set up, apache server needs a restart for changes to take place, more information in the Slack-Channel.

**Comment by kurzum** [comment]
some things for table.html:
- why not use http://listjs.com/ or similar, sortable and searchable and off-the-shelf solution
- there are many files that have only 1 byte, so they are empty? http://downloads.dbpedia.org/links/backlinks/ In this case they are either wrong or should not be created
- chile can restart the server
- could you rename table.html into index.html

**Comment by RPOD** [comment]
I will insert a check for empty sets to make sure files without a linkset aren't created. Will also take a look at listjs. Will rename table.html right away.

**Comment by RPOD** [comment]
List.js is inserted, table.html has been renamed, the HTTP authentication works as intended, the empty triples were being removed. 

Remaining issue is the 403 error when requesting the files, which seems to be an issue with nginx.

**Comment by RPOD** [comment]
Fixed 403 error issues, links can now be downloaded.
