### ISSUE TITLE
metadata.ttl description and download link

### ISSUE THREAD

**Issue by kurzum** [dbpedia/links#28]
`<#1> a void:Linkset ;
	dc:author <amit> ;
	dbp:ntriplefilelocation <http://downloads.dbpedia.org/2016-04/links/nytimes_links.ttl.bz2> ;
	void:objectsTarget <http://data.nytimes.com/> ;
	dct:description "nytimes information copied statically" .`

1. extend description
2. test whether full external URI download works

**Comment by akirsche** [comment]
- Elaborated the contents of the README.md and of the dct:description property
- Modified the ntriplelocation for static links to external URIs.
