### ISSUE TITLE
metadata.ttl validation

### ISSUE THREAD

**Issue by kurzum** [dbpedia/links#35]
shacl
- [ ] sh:xone only one way
- [ ] if two ways exist, take the best one, in general not the static

error reports
- [x] should go to @holycrab13 via info.json
- [x] via travis CI to people who send pull requests

the easiest is if validate repo produces the input data for Jan in json https://www.mkyong.com/java/json-simple-example-read-and-write-json/

**Comment by akirsche** [comment]
sh:xone is not implemented yet in RDFUnit. Actually, no logical operator is implemented yet.

**Comment by akirsche** [comment]
Our implementation supports now multiple contribution methods per linkset, merging their results to a single NT-file
