### ISSUE TITLE
update NYTimes semantic URLs

### ISSUE THREAD

**Issue by chile12** [dbpedia/links#40]
I transfered this issue from the extraction framework github.
Originaly posted by @VladimirAlexiev

http://dbpedia.org/page/3M says that `nyt:3M` is 
http://data.nytimes.com/N38115567920937854392.
However, that is long obsolete and doesn't resolve.

If you go to https://tools.wmflabs.org/sqid/#/browse?type=properties 
and do "filter labels" by "new york" or "nyt", you'll see 5 new URL patterns that work.
- Eg for "New York Times Semantic Concept: Organization": 
http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_org/3M%20Company.json?fields=all&api-key=
- The odd one amongst these 5 is "NYT topic ID":
https://www.wikidata.org/wiki/Property:P3221

(Note:  I wrote this in some notes Dec 2016, so don't remember what is "odd" about P3221, and have no clue how to go from `N38115567920937854392` to `nytd_org/3M Company`)

**Comment by VladimirAlexiev** [comment]
- now there's only https://www.wikidata.org/wiki/Property:P3221 "NYT topic ID", which carries a type prefix eg `person/` or `destination/`
- on sqid: https://tools.wmflabs.org/sqid/#/view?id=P3221&lang=en
- its formatter URL is `http://www.nytimes.com/topic/$1`
- if I browse eg by people http://topics.nytimes.com/top/reference/timestopics/people/index.html,
the individual pages are eg http://topics.nytimes.com/top/reference/timestopics/people/b/neela_banerjee/index.html
- then again, Lionel Messi is not in that list, but https://www.nytimes.com/topic/person/lionel-messi works. So the above `timestopics/people` is different from `topic/person`, why do they have two?
- https://www.nytimes.com/topic/destination/new-zealand also works

**Comment by VladimirAlexiev** [comment]
https://github.com/dbpedia/links/blob/master/links/dbpedia.org/nytimes/metadata.ttl says the author is `<amit>` and has dbp:ntriplefilelocation http://downloads.dbpedia.org/2016-04/links/nytimes_links_fixed.nt.bz2 (not clear when it's copied and from where)

**Comment by chile12** [comment]
So I talked to Amit about this. He told me that no one from NYT is responding regarding updates to the Linkset. Since we dont have any LD references, I would suggest just deleting this all together

**Comment by chile12** [comment]
This will probably need a crawl of the nyt api to recreate this linkset (a la: http://dlab.berkeley.edu/blog/scraping-new-york-times-articles-python-tutorial)

The link information is in there still:
http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_geo/Kansas?fields=all&api-key=

**Comment by chile12** [comment]
Ok the crawl is underway!
I've written a script to extract the links to DBpedia, based the direct links to DBpedia and links to Wikipedia, creating links like:

```
<http://dbpedia.org/resource/Beach> <http://www.w3.org/2002/07/owl#sameAs> <http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_des/Beaches> .
<http://dbpedia.org/resource/Bean> <http://www.w3.org/2002/07/owl#sameAs> <http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_des/Beans> .
<http://dbpedia.org/resource/Bear> <http://www.w3.org/2002/07/owl#sameAs> <http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_des/Bears> .
<http://dbpedia.org/resource/401(k)> <http://www.w3.org/2004/02/skos/core#narrower> <http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_des/401(k),%20403(b)%20and%20457%20Plans> .
<http://dbpedia.org/resource/Kansas> <http://www.w3.org/2002/07/owl#sameAs> <http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_geo/Kansas> .
<http://dbpedia.org/resource/Kansas> <http://www.w3.org/2002/07/owl#sameAs> <http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_geo/Kansas> .
```
Since only some resources have pertaining topic pages or similar, I would suggest going with the inconvenient but somewhat resolvable api IRIs, what do you think?

**Comment by kurzum** [comment]
Hi @chile12,
I don't see the script:
https://github.com/dbpedia/links/tree/master/links/dbpedia.org/nytimes

Can you commit it? 
maybe set the updateFrequency property on something that makes sense like 20 or 30 days, depending on how time intensive the script is. 
Sebastian

**Comment by kurzum** [comment]
The guide has been updated: 
https://github.com/dbpedia/links/wiki/How-To-Contribute-Links-to-DBpedia#guide

**Comment by chile12** [comment]
There are two scripts: one for crawling and one for extracting the links from the json results.
I will forward them after the first crawl finished without major errors. 

You can then deploy them as often as you want.
Note: the complete crawl takes some days...

But I'm more interested in your opinion on what IRIs to use, since the nyt api IRIs above need an api-key to be resolved, yet I don't see any other possible representation...

**Comment by kurzum** [comment]
@VladimirAlexiev we reimplemented the whole linking framework. It runs daily now and produces this:
http://dbpedia.github.io/links/tools/linkviz/

**Comment by kurzum** [comment]
@VladimirAlexiev @chile12 momentarily the links are old and fixed (see guide), please feel free to delete this and just add something else.

**Comment by VladimirAlexiev** [comment]
Thanks, looks good!

**Comment by chile12** [comment]
NYT links are available.

**Comment by VladimirAlexiev** [comment]
I checked the first few several and they seem perfect. Even http://dbpedia.org/resource/Açaí_palm maps to Acai berries.
Cheers
