### ISSUE TITLE
Broken link http://wikidata.dbpedia.org/resource/Q121594 at http://dbpedia.org/page/Professor

### ISSUE THREAD

**Issue by nicolas-raoul** [dbpedia/links#49]
1. Go to http://dbpedia.org/page/Professor
2. Click on the Wikidata link
3. Error page appears

Feel free to copy this report to any more appropriate issue tracker.
Thanks!

**Comment by kurzum** [comment]
The link to http://wikidata.dbpedia.org/resource/Q121594 works. 
http://wikidata.dbpedia.org/resource/Q121594 is discontinued.

**Comment by nicolas-raoul** [comment]
Then you must fix the http://dbpedia.org/page/Professor page (and all similar pages), to **fix the broken link**.

Please reopen until this is fixed.
